var Stamplay = require('../lib/stamplay')
var assert = require('assert')

assert.throws(function(){myApp = new Stamplay('a')})
myAppVersion = new Stamplay('a','b', 'v0')
assert.equal(myAppVersion.appId,'a')
assert.equal(myAppVersion.apiKey,'b')
assert.equal(myAppVersion.version,'v0')
myApp = new Stamplay('a','b')
assert.equal(myApp.appId,'a')
assert.equal(myApp.apiKey,'b')
assert.equal(myApp.version,'v1')
assert.equal(typeof myApp.Object, 'function')
assert.equal(typeof myApp.User, 'object')
assert.equal(typeof myApp.Webhook, 'function')
assert.equal(typeof myApp.Query, 'function')
assert.equal(typeof myApp.Codeblock, 'function')
assert.equal(typeof myApp.Stripe, 'object')
assert.equal(typeof myApp.auth, 'undefined')